import React, { useState, useEffect } from 'react';
import { FiDollarSign, FiDownload, FiFileText, FiTrendingUp, FiRefreshCw } from 'react-icons/fi';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';
import API from '../api';

const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

export default function SalaryPage() {
  const [salaries, setSalaries] = useState([]);
  const [loading, setLoading] = useState(false);

  const fetchSalaries = async () => {
    setLoading(true);
    try {
      const res = await API.get('/salary/my');
      setSalaries(res.data);
    } catch (err) {
      console.error('Failed to fetch salaries:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchSalaries(); }, []);

  const chartData = salaries.slice().reverse().map(s => ({
    name: `${monthNames[s.month - 1]} ${s.year}`, net: Math.round(s.netPay / 1000)
  }));

  const totalEarnings = salaries.reduce((a, s) => a + s.netPay, 0);
  const totalTax = salaries.reduce((a, s) => a + s.tax, 0);
  const avgSalary = salaries.length > 0 ? Math.round(totalEarnings / salaries.length) : 0;

  const downloadPayslip = (salary) => {
    const text = `
═══════════════════════════════════════
        FLASHEMS PAYSLIP
═══════════════════════════════════════
Employee: ${localStorage.getItem('name')}
Period: ${monthNames[salary.month - 1]} ${salary.year}
───────────────────────────────────────
EARNINGS
  Basic Pay:        ₹${salary.basic.toLocaleString()}
  HRA:              ₹${salary.hra.toLocaleString()}
  Bonus:            ₹${salary.bonus.toLocaleString()}
───────────────────────────────────────
DEDUCTIONS
  PF/ESI:           ₹${salary.deductions.toLocaleString()}
  Tax:              ₹${salary.tax.toLocaleString()}
───────────────────────────────────────
NET PAY:            ₹${salary.netPay.toLocaleString()}
═══════════════════════════════════════
    `.trim();
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `payslip_${monthNames[salary.month - 1]}_${salary.year}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="animate-in">
      <div className="flex justify-between items-end mb-6">
        <div>
          <div className="page-label">Compensation</div>
          <h1 className="page-title">Salary & Payslips</h1>
          <p className="page-subtitle">{salaries.length} payslips from database</p>
        </div>
        <button className="btn btn-outline" onClick={fetchSalaries} disabled={loading}><FiRefreshCw size={14} /> Refresh</button>
      </div>

      {/* Summary Cards */}
      <div className="stats-grid mb-6">
        <div className="stat-card">
          <div className="stat-icon" style={{ background: '#eceeff', color: '#2b3bf7' }}><FiDollarSign /></div>
          <div className="stat-value">₹{(salaries[0]?.netPay || 0).toLocaleString()}</div>
          <div className="stat-label">Last Net Pay</div>
        </div>
        <div className="stat-card">
          <div className="stat-icon" style={{ background: '#d1fae5', color: '#10b981' }}><FiTrendingUp /></div>
          <div className="stat-value">₹{avgSalary.toLocaleString()}</div>
          <div className="stat-label">Average Monthly</div>
        </div>
        <div className="stat-card">
          <div className="stat-icon" style={{ background: '#fee2e2', color: '#ef4444' }}><FiFileText /></div>
          <div className="stat-value">₹{totalTax.toLocaleString()}</div>
          <div className="stat-label">Total Tax Paid</div>
        </div>
        <div className="stat-card">
          <div className="stat-icon" style={{ background: '#fef3c7', color: '#f59e0b' }}><FiDollarSign /></div>
          <div className="stat-value">₹{totalEarnings.toLocaleString()}</div>
          <div className="stat-label">Total Earnings</div>
        </div>
      </div>

      {loading ? (
        <div className="flex justify-center py-10"><div className="spinner"></div></div>
      ) : salaries.length === 0 ? (
        <div className="card empty-state">
          <h3>No payslips yet</h3>
          <p className="text-sm text-muted">Your payslips will appear here once generated by HR/Admin.</p>
        </div>
      ) : (
        <>
          {/* Salary Trend Chart */}
          <div className="card mb-6">
            <h3 className="font-bold text-sm mb-4">Net Pay Trend (₹ thousands)</h3>
            <ResponsiveContainer width="100%" height={220}>
              <BarChart data={chartData}>
                <XAxis dataKey="name" tick={{ fontSize: 11 }} />
                <YAxis tick={{ fontSize: 11 }} />
                <Tooltip formatter={(val) => `₹${val}K`} />
                <Bar dataKey="net" fill="#2b3bf7" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>

          {/* Payslips Table */}
          <div className="card">
            <h3 className="font-bold text-sm mb-4">Payslip History</h3>
            <div className="table-container">
              <table className="data-table">
                <thead>
                  <tr><th>Period</th><th>Basic</th><th>HRA</th><th>Bonus</th><th>Deductions</th><th>Tax</th><th>Net Pay</th><th>Action</th></tr>
                </thead>
                <tbody>
                  {salaries.map(s => (
                    <tr key={s._id}>
                      <td className="font-medium">{monthNames[s.month - 1]} {s.year}</td>
                      <td>₹{s.basic.toLocaleString()}</td>
                      <td>₹{s.hra.toLocaleString()}</td>
                      <td className={s.bonus > 0 ? 'text-success font-bold' : ''}>₹{s.bonus.toLocaleString()}</td>
                      <td className="text-danger">-₹{s.deductions.toLocaleString()}</td>
                      <td className="text-danger">-₹{s.tax.toLocaleString()}</td>
                      <td className="font-bold">₹{s.netPay.toLocaleString()}</td>
                      <td><button onClick={() => downloadPayslip(s)} className="btn btn-secondary btn-sm"><FiDownload size={12} /> Download</button></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
